language: python
python:
  - "2.7"
install:
  - wget https://raw.github.com/globaleaks/Tor2web-3.0/master/requirements.txt
  - pip install -r requirements.txt
script:
  - sudo -i bash -x -c 'apt-get update -y'
  - sudo -i bash -x -c 'mkdir -p /data/globaleaks'
  - sudo -i bash -x -c 'chown travis:travis /data/globaleaks'
  - sudo -i bash -x -c 'mkdir -p /data/globaleaks/deb/'
  - git clone https://github.com/globaleaks/Tor2web-3.0 /data/globaleaks/Tor2web-3.0
  - /data/globaleaks/Tor2web-3.0/scripts/build-testing-package.sh -v${TRAVIS_BRANCH} -y
